name: "Tag"
description: "tag build"
author: "Norm Ross"
outputs: 
inputs:
  github_token:
    description: "Required for permission to tag the repo."
    required: true
  new_tag:
    description: "tag to use"
    required: false
    default: "patch"
runs:
  using: "node12"
  main: "index.js"
